language: java

env:
  global:
    - MAVEN_SKIP_RC=true
    - MAVEN_OPTS="-Xms512m -Xmx2048m"

jdk:
  - oraclejdk8

before_script:
  - export MAVEN_SKIP_RC=true

install: 
  - ( mvn install -Pdistribution -DskipTests=true -B -V -q ) & ( MYPID=$!; while [  $(ps -ef | grep $MYPID | grep -v grep | wc -l) -gt 0 ]; do    sleep 10;     date; done; )

script:
  - mvn test -B

sudo: false
